### ISSUE TITLE
Support `tee`

### ISSUE THREAD

**Issue by pkolaczk** [yskszk63/tokio-pipe#27]
I'd like to be able to copy data from one pipe to two more than one destination.
Linux offers a `tee` function for that. Can you add one, similar to `splice_to` ?

**Comment by NobodyXu** [comment]
It's already supported [`tokio_pipe::tee`](https://docs.rs/tokio-pipe/0.2.11/tokio_pipe/fn.tee.html).

**Comment by pkolaczk** [comment]
Indeed, I missed that. Thanks.
